name: 🚀 End-to-end tests

inputs:
  url:
    required: false
    type: string
secrets:
  auth-bypass-token:
    required: false

runs:
  using: 'composite'
  steps:
    - name: ⬇️ Checkout repo
      uses: actions/checkout@v4

    - name: ⎔ Setup node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: 📥 Install dependencies
      run: npm ci

    - name: 📦 Build
      run: npm run build

    - name: 💾 Turbo cache
      id: turbo-cache
      uses: actions/cache@v3
      with:
        path: |
          node_modules/.cache/turbo
          **/.turbo
        key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          turbo-${{ github.job }}-${{ github.ref_name }}-

    - name: 📄 Get installed Playwright version
      run: echo "PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright -m 1 | sed 's/.*@//')"  >> $GITHUB_ENV

    - name: 💾 Cache Playwright binaries
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

    - name: 💽 Install Playwright Browsers (all)
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps

    - name: 💽 Install Playwright (only system deps)
      if: steps.playwright-cache.outputs.cache-hit == 'true'
      run: npx playwright install-deps

    - name: 🍄 Run Playwright tests
      run: |
        export AUTH_BYPASS_TOKEN=${{secrets.auth-bypass-token}}
        export DEPLOYMENT_URL=${{inputs.url}}
        npx playwright test

    - name: 🗒 Report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: ./playwright-report/
        retention-days: 30
